# ----------------------------
# PROD PROFILE (Postgres)
# ----------------------------

server.port=8080

# DB (Postgres)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Dialect Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JWT (prod) ---
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-ms=3600000